### PR TITLE
upgrade to python 3

### PR DESCRIPTION
**Pull request by TomMalkin**
All tests passing on python 3.6.4. 

Haven't yet checked your examples or the bytecode compiler

### CODE REVIEW

**Comment by cslarsen** [comment]
Looks good, I'll merge when everything passes.

**Comment by TomMalkin** [comment]
Are you wanting to maintain python 2 support? Or are you ok with only supporting python 3?

**Comment by cslarsen** [comment]
No, I don't want to abandon Python 2.7 support and suddenly break things for existing users.

**Comment by TomMalkin** [comment]
tests passing for python 2.7, 3.6 and 3.7

I was changing all sorts like formatting and stuff, but I realised that wasn't in line with what this pull request was trying to do, so the commits are the minimum required to get the tests to pass for all versions.

There were some circular imports (that were breaking because all imports are now absolute) that I had to hotfix by placing some imports within function definitions - obviously refactoring is the better solution but again this is just the minimum.

setup.py now has six as an install requirement.

.gitignore also updated to one similar to https://github.com/github/gitignore/blob/master/Python.gitignore

All the examples are working as well.

**Comment by cslarsen** [comment]
Awesome stuff. Only minor thing, can you please minimize the `.gitignore` file as well? You can add your own, local ignores to `.git/info/exclude` or something like that if you need it, but I don't want it in the official one. If you do that, i'll merge it.

**Comment by cslarsen** [comment]
Also, if you want to, you can add your name in README undert the BSD license text. Something like `Additional patches made by:` or something like that. Your patch will of course follow the same license as the original project, just to make that clear.

**Comment by TomMalkin** [comment]
Updated both, thanks! This is my first pull request so I really appreciate the pointers.

**Review by cslarsen — APPROVED** [review]

**Comment by cslarsen** [comment]
Definitely an improvement, thanks!

**Pull request merged**
